                          theme: jekyll-theme-minimal
                          title: Wyatts' Home Page
              description: Bookmark this to keep an eye on my project updates!
<a href="file:///C:/Users/owner/Documents/index.htm">Project 1.</a>
